config/routes.rb
SampleApp::Application.routes.draw do

  resources :work_entries
  resources :users

  match '/about', :to => 'pages#about'
  match '/wow', :to => 'pages#wow'

  root :to => 'pages#home'

end #final end

app/models/user.rb
class User < ActiveRecord::Base
  #has many DB attribute:
  has_many :work_entries
end

app/models/work_entry.rb
class WorkEntry < ActiveRecord::Base

 # attr_accessible :date, :task, :time_in, :time_out, :description, :iteration
  #belongs to DB attribute:
  belongs_to :user
  
  def hours
    hours = (self.end - self.start) / 3600
    hours = "%.1f" % hours
    return hours
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @title = "Home"
  end

  def about
    @title = "About"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])
    
    #next 2 lines added: - C.Dorros
    #@work_entries = @user.work_entries.paginate(:page => params[:page])
    @work_entries = @user.work_entries(:page => params[:page])
    @title = @user.name

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/work_entries_controller.rb
class WorkEntriesController < ApplicationController

#AUTO GENERATED METHODS:
  # GET /work_entries
  # GET /work_entries.xml
  def index
    @work_entries = WorkEntry.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @work_entries }
    end
  end

  # GET /work_entries/1
  # GET /work_entries/1.xml
  def show
    @work_entry = WorkEntry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @work_entry }
    end
  end

  # GET /work_entries/new
  # GET /work_entries/new.xml
  def new
    @work_entry = WorkEntry.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @work_entry }
    end
  end

  # GET /work_entries/1/edit
  def edit
    @work_entry = WorkEntry.find(params[:id])
  end

  # POST /work_entries
  # POST /work_entries.xml
  def create
    @work_entry = WorkEntry.new(params[:work_entry])

    respond_to do |format|
      if @work_entry.save
        format.html { redirect_to(@work_entry, :notice => 'Work entry was successfully created.') }
        format.xml  { render :xml => @work_entry, :status => :created, :location => @work_entry }
        format.js
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @work_entry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /work_entries/1
  # PUT /work_entries/1.xml
  def update
    @work_entry = WorkEntry.find(params[:id])

    respond_to do |format|
      if @work_entry.update_attributes(params[:work_entry])
        format.html { redirect_to(@work_entry, :notice => 'Work entry was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @work_entry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /work_entries/1
  # DELETE /work_entries/1.xml
  def destroy
    @work_entry = WorkEntry.find(params[:id])
    @work_entry.destroy

    respond_to do |format|
      format.html { redirect_to(work_entries_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # Return a title on a per-page basis
  def title
    base_title = "Time-tracker"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/work_entries_helper.rb
module WorkEntriesHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= image_tag("logo.png", :alt => "Time Tracker", :class => "round") %>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Users", users_path %></li>
      <li><%= link_to "Work Entries", work_entries_path %></li>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
      <!-- This javascript include tag must be here to destroy to work  -->
    <%= javascript_include_tag :defaults %>
    <%#= javascript_include_tag 'jquery', 'application' %>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>
Welcome to the Time-Tracker app! This app was designed to allow students 
in the CMU Software Engineering Course track their hours spent on coursework. 
Now go start working on the "rail-road!" (cheesy, yes)
</p>

app/views/pages/home.html.erb
<h1>Time-tracker application</h1>

<p>
This is the home page for the time-tracker application. <br />
Make sure to use it each time you work on something for the Software Engineering course to track your hours!
</p>

<p>
Please use the navigation bar at the top right of the screen! Thanks!
</p>

<p>
PS: <%= link_to 'Click here to be Wowed', wow_path %>
</p>

app/views/pages/wow.html.erb
<%= image_tag("wow.gif", :alt => "WOW!", :class => "round") %>

<br/>
<br/>
..just kidding. Wish I had more time to actually "wow" you.

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- FIELDS -->
  <div class="field">
    <%= f.label :name  %>
    <%= f.text_field :name  %>
  </div>

  <div class="field">
    <%= f.label :user_name  %>
    <%= f.text_field :user_name  %>
  </div>

  <!-- ACTIONS -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>All Users</h1>

<p>The following is a list of all users:</p>

<%= link_to 'New User', new_user_path %>
<br />

<table>
  <tr>
    <th>User ID</th>
    <th>Name</th>
    <th>Username</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.id  %></td>
    <td><%= user.name  %></td>
    <td><%= user.user_name  %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<% if @user.work_entries.empty? %>
  User "<%= @user.name %>" (id=<%= @user.id %>) has no Work Entries. Get to work! <br />
<% end %>



<% unless @user.work_entries.empty? %>
  <!-- WORK ENTRIES -->
  <h2>Work Entries</h2>
  <p><b>for user: <%= @user.name %> (id=<%= @user.id %>)</b></p>

  <!-- Work Entries Table  -->
  <table class="work_entries" summary="Work Entries">
    <tr>
      <th>Task</th>
      <th>Hours</th>
      <th>Iteration</th>
      <th>User</th>
    </tr>
    <%= render @work_entries %>
  </table>
<% end %>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/work_entries/_form.html.erb
<%= form_for :work_entry, :remote=>true do |f| %>


  <div class="field">
    <%= f.label :task %><br />
    <%= f.text_field :task %>
  </div>
  <div class="field">
    <%= f.label :start %><br />
    <%= f.datetime_select:start %>
  </div>
  <div class="field">
    <%= f.label :end %><br />
    <%= f.datetime_select :end %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :iteration %><br />
    <%= f.text_field :iteration %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.select :user_id, User.all.collect {|user| [ user.user_name, user.id ]},:include_blank => false %>  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/work_entries/_form_static.html.erb
<%= form_for (@work_entry) do |f| %>
  <% if @work_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work_entry.errors.count, "error") %> prohibited this work entry from being saved:</h2>

      <ul>
      <% @work_entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :task %><br />
    <%= f.text_field :task %>
  </div>
  <div class="field">
    <%= f.label :start %><br />
    <%= f.datetime_select:start %>
  </div>
  <div class="field">
    <%= f.label :end %><br />
    <%= f.datetime_select :end %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :iteration %><br />
    <%= f.text_field :iteration %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.select :user_id, User.all.collect {|user| [ user.user_name, user.id ]},:include_blank => false %>  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/work_entries/_work_entry.html.erb
<tr>
  <td><%= work_entry.task  %></td>
  <td><%= work_entry.hours %></td>
  <td><%= work_entry.iteration %></td>
  <td><%= User.find(work_entry.user_id).name %></td>
  <td><%= link_to 'Show', work_entry %></td>
  <td><%= link_to 'Edit', edit_work_entry_path(work_entry) %></td>
  <td><%= link_to 'Destroy', work_entry, :confirm => 'Are you sure?', :method => :delete %></td>
</tr>

app/views/work_entries/_work_entry_list.html.erb
<table>
  <tr>
    <th>Task</th>
    <th>Hours</th>
    <th>Iteration</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</table>

<table>
<!-- New rows go here -->
<div id="newrow">
</div>

<% @work_entries.each do |work_entry| %>
  <tr>
    <td><%= work_entry.task %></td>

    <td><%= work_entry.hours %></td>
    <td><%= work_entry.iteration %></td>
    <td><%= User.find(work_entry.user_id).name %></td>
    <td><%= link_to 'Show', work_entry %></td>
    <td><%= link_to 'Edit', edit_work_entry_path(work_entry) %></td>
    <td><%= link_to 'Destroy', work_entry, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

app/views/work_entries/create.js.erb
<!-- add new work entry -->
$("#newrow").append("<%= escape_javascript(render(:partial => @work_entry)) %>");

app/views/work_entries/edit.html.erb
<h1>Editing work_entry</h1>

<%= render 'form_static' %>

<%= link_to 'Show', @work_entry %> |
<%= link_to 'Back', work_entries_path %>

app/views/work_entries/index.html.erb
<h1>All Work Entries</h1>

<p>The following is a list of work entries for all users:</p>

<%= render 'form' %>
<br />

<div id="work_entries">
<%= render 'work_entry_list' %>
</div>

app/views/work_entries/new.html.erb
<h1>New work_entry</h1>

<%= render 'form' %>

<%= link_to 'Back', work_entries_path %>

app/views/work_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Task:</b>
  <%= @work_entry.task %>
</p>

<p>
  <b>Start:</b>
  <%= @work_entry.start %>
</p>

<p>
  <b>End:</b>
  <%= @work_entry.end %>
</p>

<p>
  <b>Hours:</b>
  <%= @work_entry.hours %>
</p>

<p>
  <b>Description:</b>
  <%= @work_entry.description %>
</p>

<p>
  <b>Iteration:</b>
  <%= @work_entry.iteration %>
</p>

<p>
  <b>User:</b>
  <%= @work_entry.user_id %>
</p>


<%= link_to 'Edit', edit_work_entry_path(@work_entry) %> |
<%= link_to 'Back', work_entries_path %>